module.exports = {
  mongoURI: process.env.MONGO_URI,
  secret: process.env.SECRET,
  mixpanelToken: process.env.MIXPANEL_TOKEN,
  environment: process.env.ENVIRONMENT,
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID,
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN,
  kevin: process.env.KEVIN,
  brett: process.env.BRETT,
  spotifyClientId: process.env.SPOTIFY_CLIENT_ID,
  spofityClientSecret: process.env.SPOTIFY_CLIENT_SECRET,
  accessKeyId: process.env.ACCESS_KEY_ID,
  secretAccessKey: process.env.SECRET_ACCESS_KEY,
  Bucket: process.env.BUCKET,
  mailchimpURI: process.env.MAILCHIMP_URI,
  mailchimpApiKey: process.env.MAILCHIMP_API_KEY,
  mailchimpListId: process.env.MAILCHIMP_LIST_ID,
};
